#!/bin/sh

. /lib/functions.sh

case "$(board_name)" in
	xiaomi,ax3600|\
	xiaomi,ax3600-stock)
		;;
	*)
		exit 0
		;;
esac

uci -q get network.globals > /dev/null || uci -q set network.globals='globals'
uci -q set network.globals.packet_steering='0'
uci -q commit network

if uci -q get firewall.@defaults[0] > /dev/null; then
	uci -q set firewall.@defaults[0].flow_offloading='0'
	uci -q set firewall.@defaults[0].flow_offloading_hw='0'
	uci -q set firewall.@defaults[0].fullcone='1'
	uci -q set firewall.@defaults[0].fullcone6='1'
	uci -q commit firewall
fi

if uci -q get turboacc.config > /dev/null; then
	uci -q set turboacc.config.sw_flow='0'
	uci -q set turboacc.config.hw_flow='0'
	uci -q set turboacc.config.sfe_flow='0'
	uci -q set turboacc.config.fullcone_nat='1'
	uci -q set turboacc.config.fullcone6='1'
	uci -q set turboacc.config.bbr_cca='1'
	uci -q commit turboacc
fi

uci -q get luci_plugins.global > /dev/null || uci -q set luci_plugins.global='global'
uci -q set luci_plugins.global.enabled='1'
uci -q commit luci_plugins

exit 0
