#!/bin/sh

. /lib/functions.sh

case "$(board_name)" in
	xiaomi,ax3600|\
	xiaomi,ax3600-stock)
		;;
	*)
		exit 0
		;;
esac

uci -q get network.globals > /dev/null || uci -q set network.globals='globals'
uci -q set network.globals.packet_steering='0'
uci -q commit network

if uci -q get firewall.@defaults[0] > /dev/null; then
	uci -q set firewall.@defaults[0].flow_offloading='0'
	uci -q set firewall.@defaults[0].flow_offloading_hw='0'
	uci -q set firewall.@defaults[0].fullcone='1'
	uci -q set firewall.@defaults[0].fullcone6='1'
	uci -q commit firewall
fi

touch /etc/config/sqm
uci -q batch <<-SQM
	set sqm.wan='queue'
	set sqm.wan.enabled='0'
	set sqm.wan.interface='wan'
	set sqm.wan.download='0'
	set sqm.wan.upload='0'
	set sqm.wan.qdisc='cake'
	set sqm.wan.script='piece_of_cake.qos'
	set sqm.wan.qdisc_advanced='1'
	set sqm.wan.squash_dscp='1'
	set sqm.wan.squash_ingress='1'
	set sqm.wan.ingress_ecn='ECN'
	set sqm.wan.egress_ecn='NOECN'
	set sqm.wan.qdisc_really_really_advanced='1'
	set sqm.wan.iqdisc_opts='nat dual-dsthost ingress'
	set sqm.wan.eqdisc_opts='nat dual-srchost ack-filter'
	set sqm.wan.linklayer='ethernet'
	set sqm.wan.overhead='44'
	set sqm.wan.linklayer_advanced='1'
	set sqm.wan.tcMTU='2047'
	set sqm.wan.tcTSIZE='128'
	set sqm.wan.tcMPU='64'
	set sqm.wan.debug_logging='0'
	set sqm.wan.verbosity='5'
	commit sqm
SQM

uci -q get luci_plugins.global > /dev/null || uci -q set luci_plugins.global='global'
uci -q set luci_plugins.global.enabled='1'
uci -q commit luci_plugins

exit 0
