#!/bin/sh

# === IPv6: SLAAC IP + DHCPv6 DNS (stateless) ===
uci -q batch <<-SETV6
	set dhcp.lan.ra='server'
	set dhcp.lan.dhcpv6='server'
	set dhcp.lan.ra_management='2'
	commit dhcp
SETV6

# === LuCI: auto-refresh homepage stats + DHCP leases ===
uci -q batch <<-SETREFRESH
	set luci.main.pollinterval='3'
	commit luci
SETREFRESH

# === LED: network LEDs follow WAN ===
uci -q batch <<-SETLED
	delete system.led_network_yellow
	delete system.led_network_blue
	set system.led_network_yellow='led'
	set system.led_network_yellow.name='WAN Link'
	set system.led_network_yellow.sysfs='yellow:network'
	set system.led_network_yellow.trigger='netdev'
	set system.led_network_yellow.dev='wan'
	set system.led_network_yellow.mode='link'
	set system.led_network_blue='led'
	set system.led_network_blue.name='WAN Activity'
	set system.led_network_blue.sysfs='blue:network'
	set system.led_network_blue.trigger='netdev'
	set system.led_network_blue.dev='wan'
	set system.led_network_blue.mode='tx rx'
	commit system
SETLED

exit 0
